import type { YouTubeVideo, VideoCategory } from '../types';

const now = new Date();
function hoursBack(h: number): Date {
  return new Date(now.getTime() - h * 3600 * 1000);
}

function calcEngagement(views: number, likes: number, comments: number): number {
  if (views === 0) return 0;
  return parseFloat((((likes + comments) / views) * 100).toFixed(2));
}

function calcGrowthScore(viewsPerHour: number, engagement: number, hoursAgo: number): number {
  const recencyBoost = Math.max(0, 1 - hoursAgo / 48);
  const raw = viewsPerHour * 0.0001 * 40 + engagement * 3 + recencyBoost * 20;
  return Math.min(100, parseFloat(raw.toFixed(1)));
}

const rawVideos: Omit<YouTubeVideo, 'viewsPerHour' | 'engagementRate' | 'growthScore'>[] = [
  // Gaming
  {
    id: 'dQw4w9WgXcQ',
    title: 'I Survived 100 Days in Minecraft Hardcore and Here\'s What Happened',
    channelName: 'LegendaryGamer',
    channelId: 'UC123gaming',
    thumbnailUrl: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    category: 'Gaming',
    type: 'long',
    durationSeconds: 3240,
    viewCount: 4_800_000,
    likeCount: 320_000,
    commentCount: 18_000,
    publishedAt: hoursBack(6),
    hoursAgo: 6,
    tags: ['minecraft', 'hardcore', '100days', 'survival'],
  },
  {
    id: 'kJQP7kiw5Fk',
    title: 'This NEW Game is BREAKING the Internet in 2025',
    channelName: 'GameFrenzy',
    channelId: 'UC456gaming',
    thumbnailUrl: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    category: 'Gaming',
    type: 'short',
    durationSeconds: 58,
    viewCount: 9_200_000,
    likeCount: 780_000,
    commentCount: 42_000,
    publishedAt: hoursBack(4),
    hoursAgo: 4,
    tags: ['viral', 'newgame', 'trending', 'shorts'],
  },
  {
    id: 'M7lc1UVf-VE',
    title: 'Pro Player DESTROYS World Record — No One Expected This',
    channelName: 'SpeedRunKing',
    channelId: 'UC789gaming',
    thumbnailUrl: 'https://i.ytimg.com/vi/M7lc1UVf-VE/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
    category: 'Gaming',
    type: 'long',
    durationSeconds: 1860,
    viewCount: 2_300_000,
    likeCount: 195_000,
    commentCount: 9_800,
    publishedAt: hoursBack(14),
    hoursAgo: 14,
    tags: ['worldrecord', 'speedrun', 'pro', 'gaming'],
  },

  // Finance
  {
    id: 'JGwWNGJdvx8',
    title: 'How I Made $50,000 in ONE Week with AI Trading (Step by Step)',
    channelName: 'WealthBuilder',
    channelId: 'UC123finance',
    thumbnailUrl: 'https://i.ytimg.com/vi/JGwWNGJdvx8/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    category: 'Finance',
    type: 'long',
    durationSeconds: 2580,
    viewCount: 3_700_000,
    likeCount: 290_000,
    commentCount: 22_000,
    publishedAt: hoursBack(8),
    hoursAgo: 8,
    tags: ['trading', 'AI', 'money', 'investing'],
  },
  {
    id: 'G1IbRujko-A',
    title: 'The Stock Market CRASH Nobody is Talking About',
    channelName: 'FinanceAlerts',
    channelId: 'UC456finance',
    thumbnailUrl: 'https://i.ytimg.com/vi/G1IbRujko-A/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=G1IbRujko-A',
    category: 'Finance',
    type: 'short',
    durationSeconds: 55,
    viewCount: 6_100_000,
    likeCount: 510_000,
    commentCount: 31_000,
    publishedAt: hoursBack(3),
    hoursAgo: 3,
    tags: ['stockmarket', 'crash', 'economy', 'investing'],
  },

  // Technology
  {
    id: 'YoXxevp1WRQ',
    title: 'GPT-5 is HERE and It Changes EVERYTHING (Full Review)',
    channelName: 'TechInsider',
    channelId: 'UC123tech',
    thumbnailUrl: 'https://i.ytimg.com/vi/YoXxevp1WRQ/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YoXxevp1WRQ',
    category: 'Technology',
    type: 'long',
    durationSeconds: 2100,
    viewCount: 5_400_000,
    likeCount: 430_000,
    commentCount: 28_000,
    publishedAt: hoursBack(10),
    hoursAgo: 10,
    tags: ['AI', 'GPT5', 'tech', 'future'],
  },
  {
    id: 'xvFZjo5PgG0',
    title: 'Apple\'s Secret Project LEAKED — The Internet is Going Crazy',
    channelName: 'AppleLeaks',
    channelId: 'UC456tech',
    thumbnailUrl: 'https://i.ytimg.com/vi/xvFZjo5PgG0/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=xvFZjo5PgG0',
    category: 'Technology',
    type: 'short',
    durationSeconds: 52,
    viewCount: 8_900_000,
    likeCount: 720_000,
    commentCount: 45_000,
    publishedAt: hoursBack(5),
    hoursAgo: 5,
    tags: ['apple', 'leaked', 'tech', 'shorts'],
  },
  {
    id: 'rfscVS0vtbw',
    title: 'I Built a $1M SaaS Using Only AI Tools in 30 Days',
    channelName: 'BuilderPro',
    channelId: 'UC789tech',
    thumbnailUrl: 'https://i.ytimg.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
    category: 'Technology',
    type: 'long',
    durationSeconds: 3600,
    viewCount: 2_800_000,
    likeCount: 240_000,
    commentCount: 14_500,
    publishedAt: hoursBack(20),
    hoursAgo: 20,
    tags: ['saas', 'AI', 'startup', 'nocode'],
  },

  // Fitness
  {
    id: 'hY7m5jF8J7A',
    title: '10 Minute Full Body SHRED — No Equipment Needed',
    channelName: 'FitWith',
    channelId: 'UC123fitness',
    thumbnailUrl: 'https://i.ytimg.com/vi/hY7m5jF8J7A/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=hY7m5jF8J7A',
    category: 'Fitness',
    type: 'short',
    durationSeconds: 60,
    viewCount: 7_500_000,
    likeCount: 680_000,
    commentCount: 38_000,
    publishedAt: hoursBack(7),
    hoursAgo: 7,
    tags: ['fitness', 'workout', 'noequipment', 'shorts'],
  },
  {
    id: 'pTBr72_qzcE',
    title: 'I Tried Every Viral Fitness Hack for 30 Days — Honest Results',
    channelName: 'FitnessExperiment',
    channelId: 'UC456fitness',
    thumbnailUrl: 'https://i.ytimg.com/vi/pTBr72_qzcE/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=pTBr72_qzcE',
    category: 'Fitness',
    type: 'long',
    durationSeconds: 1920,
    viewCount: 3_100_000,
    likeCount: 260_000,
    commentCount: 15_200,
    publishedAt: hoursBack(16),
    hoursAgo: 16,
    tags: ['fitness', 'experiment', 'viral', 'health'],
  },

  // Music
  {
    id: 'CevxZvSJLk8',
    title: 'Unknown Artist Goes VIRAL Overnight — Reaction',
    channelName: 'MusicVibes',
    channelId: 'UC123music',
    thumbnailUrl: 'https://i.ytimg.com/vi/CevxZvSJLk8/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=CevxZvSJLk8',
    category: 'Music',
    type: 'short',
    durationSeconds: 57,
    viewCount: 11_200_000,
    likeCount: 980_000,
    commentCount: 62_000,
    publishedAt: hoursBack(2),
    hoursAgo: 2,
    tags: ['music', 'viral', 'reaction', 'shorts'],
  },
  {
    id: 'fLexgOxsZu0',
    title: 'This Song Hit 10M Views in 24 Hours — Breaking Records',
    channelName: 'ChartBuster',
    channelId: 'UC456music',
    thumbnailUrl: 'https://i.ytimg.com/vi/fLexgOxsZu0/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=fLexgOxsZu0',
    category: 'Music',
    type: 'long',
    durationSeconds: 248,
    viewCount: 10_500_000,
    likeCount: 890_000,
    commentCount: 55_000,
    publishedAt: hoursBack(22),
    hoursAgo: 22,
    tags: ['music', 'viral', 'record', 'trending'],
  },

  // Education
  {
    id: 'UF8uR6Z6KLc',
    title: 'Learn Python in 1 Hour — Full Crash Course for Beginners',
    channelName: 'CodeWithMe',
    channelId: 'UC123edu',
    thumbnailUrl: 'https://i.ytimg.com/vi/UF8uR6Z6KLc/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc',
    category: 'Education',
    type: 'long',
    durationSeconds: 3800,
    viewCount: 2_200_000,
    likeCount: 195_000,
    commentCount: 11_000,
    publishedAt: hoursBack(30),
    hoursAgo: 30,
    tags: ['python', 'programming', 'tutorial', 'beginners'],
  },
  {
    id: 'OAJ_J3ZUVEM',
    title: 'Mind-Blowing Facts About the Universe (You Need to Know)',
    channelName: 'ScienceDaily',
    channelId: 'UC456edu',
    thumbnailUrl: 'https://i.ytimg.com/vi/OAJ_J3ZUVEM/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=OAJ_J3ZUVEM',
    category: 'Education',
    type: 'short',
    durationSeconds: 59,
    viewCount: 5_800_000,
    likeCount: 490_000,
    commentCount: 28_000,
    publishedAt: hoursBack(9),
    hoursAgo: 9,
    tags: ['science', 'universe', 'facts', 'shorts'],
  },

  // Lifestyle
  {
    id: 'tntOCGkgt98',
    title: 'My $10,000/Month Passive Income Setup (Full Tour)',
    channelName: 'LifestyleByDesign',
    channelId: 'UC123life',
    thumbnailUrl: 'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=tntOCGkgt98',
    category: 'Lifestyle',
    type: 'long',
    durationSeconds: 2760,
    viewCount: 4_100_000,
    likeCount: 350_000,
    commentCount: 21_000,
    publishedAt: hoursBack(12),
    hoursAgo: 12,
    tags: ['passive income', 'lifestyle', 'money', 'tour'],
  },
  {
    id: 'EgqAQzMJNuE',
    title: 'Morning Routine of a Millionaire — 5AM Club',
    channelName: 'MorningMinds',
    channelId: 'UC456life',
    thumbnailUrl: 'https://i.ytimg.com/vi/EgqAQzMJNuE/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=EgqAQzMJNuE',
    category: 'Lifestyle',
    type: 'short',
    durationSeconds: 58,
    viewCount: 6_700_000,
    likeCount: 590_000,
    commentCount: 34_000,
    publishedAt: hoursBack(5),
    hoursAgo: 5,
    tags: ['morning routine', 'millionaire', 'productivity', 'shorts'],
  },

  // Food
  {
    id: 'FmMNpxV6VaU',
    title: 'Gordon Ramsay Reacts to the WORST Cooking Videos on TikTok',
    channelName: 'FoodReacts',
    channelId: 'UC123food',
    thumbnailUrl: 'https://i.ytimg.com/vi/FmMNpxV6VaU/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=FmMNpxV6VaU',
    category: 'Food',
    type: 'long',
    durationSeconds: 1740,
    viewCount: 3_400_000,
    likeCount: 285_000,
    commentCount: 19_500,
    publishedAt: hoursBack(18),
    hoursAgo: 18,
    tags: ['food', 'cooking', 'viral', 'reaction'],
  },
  {
    id: 'ZXNSqqzECq4',
    title: 'Secret McDonald\'s Menu Items That Actually Exist',
    channelName: 'FoodSecrets',
    channelId: 'UC456food',
    thumbnailUrl: 'https://i.ytimg.com/vi/ZXNSqqzECq4/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ZXNSqqzECq4',
    category: 'Food',
    type: 'short',
    durationSeconds: 56,
    viewCount: 8_300_000,
    likeCount: 720_000,
    commentCount: 48_000,
    publishedAt: hoursBack(3),
    hoursAgo: 3,
    tags: ['food', 'mcdonalds', 'secrets', 'shorts'],
  },

  // Travel
  {
    id: 'W3r5C7VeXFo',
    title: 'I Spent 30 Days in Bali on $30/Day — Detailed Guide',
    channelName: 'NomadAdventures',
    channelId: 'UC123travel',
    thumbnailUrl: 'https://i.ytimg.com/vi/W3r5C7VeXFo/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=W3r5C7VeXFo',
    category: 'Travel',
    type: 'long',
    durationSeconds: 2880,
    viewCount: 2_600_000,
    likeCount: 218_000,
    commentCount: 13_400,
    publishedAt: hoursBack(24),
    hoursAgo: 24,
    tags: ['travel', 'bali', 'budget', 'nomad'],
  },

  // Science
  {
    id: 'vb-4JBkMHFk',
    title: 'Scientists Discovered Something IMPOSSIBLE in Deep Ocean',
    channelName: 'ScienceBreakthrough',
    channelId: 'UC123science',
    thumbnailUrl: 'https://i.ytimg.com/vi/vb-4JBkMHFk/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=vb-4JBkMHFk',
    category: 'Science',
    type: 'short',
    durationSeconds: 60,
    viewCount: 9_800_000,
    likeCount: 850_000,
    commentCount: 52_000,
    publishedAt: hoursBack(4),
    hoursAgo: 4,
    tags: ['science', 'ocean', 'discovery', 'shorts'],
  },

  // Comedy
  {
    id: 'Rku9RlLEBDU',
    title: 'My Neighbor Called the Police on My Robot Lawn Mower',
    channelName: 'FunnyDailyLife',
    channelId: 'UC123comedy',
    thumbnailUrl: 'https://i.ytimg.com/vi/Rku9RlLEBDU/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Rku9RlLEBDU',
    category: 'Comedy',
    type: 'short',
    durationSeconds: 55,
    viewCount: 12_400_000,
    likeCount: 1_100_000,
    commentCount: 74_000,
    publishedAt: hoursBack(1),
    hoursAgo: 1,
    tags: ['comedy', 'funny', 'neighbor', 'shorts'],
  },

  // Beauty
  {
    id: 'nkSM0h2STHs',
    title: 'I Used ONLY Drugstore Makeup for a Week — $30 Full Face',
    channelName: 'BeautyOnBudget',
    channelId: 'UC123beauty',
    thumbnailUrl: 'https://i.ytimg.com/vi/nkSM0h2STHs/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=nkSM0h2STHs',
    category: 'Beauty',
    type: 'long',
    durationSeconds: 1560,
    viewCount: 2_900_000,
    likeCount: 248_000,
    commentCount: 16_800,
    publishedAt: hoursBack(15),
    hoursAgo: 15,
    tags: ['beauty', 'makeup', 'budget', 'drugstore'],
  },

  // Sports
  {
    id: 'sGbxmsDFVnE',
    title: 'The GREATEST Sports Moments of 2025 That Broke the Internet',
    channelName: 'SportsMoments',
    channelId: 'UC123sports',
    thumbnailUrl: 'https://i.ytimg.com/vi/sGbxmsDFVnE/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=sGbxmsDFVnE',
    category: 'Sports',
    type: 'long',
    durationSeconds: 2200,
    viewCount: 5_200_000,
    likeCount: 440_000,
    commentCount: 27_000,
    publishedAt: hoursBack(11),
    hoursAgo: 11,
    tags: ['sports', 'best moments', 'viral', '2025'],
  },

  // Entertainment
  {
    id: 'DJztXj2GPfl',
    title: 'Hollywood Star QUITS Acting to Become a YouTuber — Interview',
    channelName: 'EntertainmentNow',
    channelId: 'UC123ent',
    thumbnailUrl: 'https://i.ytimg.com/vi/DJztXj2GPfl/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=DJztXj2GPfl',
    category: 'Entertainment',
    type: 'long',
    durationSeconds: 3100,
    viewCount: 4_600_000,
    likeCount: 390_000,
    commentCount: 24_500,
    publishedAt: hoursBack(9),
    hoursAgo: 9,
    tags: ['celebrity', 'interview', 'youtube', 'entertainment'],
  },

  // News
  {
    id: 'qT4WtSsRCkI',
    title: 'BREAKING: Major World Event Changes Everything in 2025',
    channelName: 'NewsNow',
    channelId: 'UC123news',
    thumbnailUrl: 'https://i.ytimg.com/vi/qT4WtSsRCkI/maxresdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=qT4WtSsRCkI',
    category: 'News',
    type: 'short',
    durationSeconds: 58,
    viewCount: 7_800_000,
    likeCount: 650_000,
    commentCount: 43_000,
    publishedAt: hoursBack(2),
    hoursAgo: 2,
    tags: ['news', 'breaking', 'world', 'shorts'],
  },
];

export const MOCK_VIDEOS: YouTubeVideo[] = rawVideos.map((v) => {
  const viewsPerHour = parseFloat((v.viewCount / Math.max(v.hoursAgo, 1)).toFixed(0));
  const engagementRate = calcEngagement(v.viewCount, v.likeCount, v.commentCount);
  const growthScore = calcGrowthScore(viewsPerHour, engagementRate, v.hoursAgo);
  return { ...v, viewsPerHour, engagementRate, growthScore };
});

export const CATEGORY_EMOJIS: Record<VideoCategory, string> = {
  Gaming: '🎮',
  Music: '🎵',
  Technology: '💻',
  Finance: '💰',
  Fitness: '💪',
  Lifestyle: '✨',
  Education: '📚',
  Entertainment: '🎬',
  News: '📰',
  Food: '🍔',
  Travel: '✈️',
  Beauty: '💄',
  Sports: '⚽',
  Science: '🔬',
  Comedy: '😂',
};

export const CPM_ESTIMATES: Record<VideoCategory, number> = {
  Finance: 22,
  Technology: 18,
  Education: 15,
  Gaming: 8,
  Fitness: 12,
  Lifestyle: 10,
  Sports: 9,
  Music: 6,
  Entertainment: 7,
  News: 11,
  Food: 9,
  Travel: 13,
  Beauty: 14,
  Science: 16,
  Comedy: 7,
};
